[package]
name = "zerosh"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "4.0.0"
nix = "0.25"
rustyline = "10.0.0"
signal-hook = "0.3.14"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
